[package]
name = "choochoo"
version = "0.0.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"
description = "Automation that starts where it stops."
repository = "https://github.com/azriel91/choochoo"
documentation = "https://docs.rs/choochoo/"
readme = "README.md"
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[dependencies]
codespan = { git = "https://github.com/brendanzab/codespan.git" }
daggy = { version = "0.7.0", default-features = false }
futures = "0.3.12"
indexmap = "1.6.1"
srcerr = "0.2.0"
tokio = { version = "1.1.0", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.2.0", features = ["fs", "rt", "sync", "io-std"] }

[patch.crates-io]
codespan-reporting = { git = "https://github.com/brendanzab/codespan.git" }
