[package]
name = "choochoo"
version = "0.0.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"
description = "Automation that starts where it stops."
repository = "https://github.com/azriel91/choochoo"
documentation = "https://docs.rs/choochoo/"
readme = "README.md"
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[dependencies]
daggy = { version = "0.7.0", default-features = false }
futures = "0.3.12"
indexmap = "1.6.1"
resman = "0.1.0"
srcerr = { version = "0.4.0", features = ["codespan"] }
tokio = { version = "1.5.0", features = ["io-util"] }

[dev-dependencies]
reqwest = { version = "0.11.3", features = ["multipart", "stream"] }
tokio = { version = "1.5.0", features = ["fs", "rt", "sync", "io-std"] }
tokio-util = { version = "0.6.6", features = ["codec"] }
