use std::{
    fmt::{self, Debug},
    future::Future,
    pin::Pin,
};

use crate::rt_model::Station;

/// Return type of the `VisitFn`.
pub type VisitFnReturn<'f, E> = Pin<Box<dyn Future<Output = Result<(), E>> + 'f>>;

/// Steps to run when a station is visited.
pub struct VisitFn<E>(pub fn(&'_ mut Station<E>) -> VisitFnReturn<'_, E>);

// We `impl Clone` to avoid the `E: Clone` bound generated by the derive.
#[cfg(not(tarpaulin_include))]
impl<E> Clone for VisitFn<E> {
    fn clone(&self) -> Self {
        Self(self.0)
    }
}

// We `impl Copy` to avoid the `E: Copy` bound generated by the derive.
impl<E> Copy for VisitFn<E> {}

impl<E> Debug for VisitFn<E> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("VisitFn(fn(&'_ mut Station<E>) -> VisitFnReturn<'_, E>)")
    }
}

impl<E> PartialEq for VisitFn<E> {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(&self.0, &other.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn debug_impl_includes_all_fields() {
        let visit_fn = VisitFn(|_| Box::pin(async { Result::<(), ()>::Ok(()) }));

        assert_eq!(
            "VisitFn(fn(&'_ mut Station<E>) -> VisitFnReturn<'_, E>)",
            format!("{:?}", visit_fn)
        );
    }

    #[test]
    fn partial_eq_returns_true_for_same_instance() {
        let visit_fn = VisitFn(|_| Box::pin(async { Result::<(), ()>::Ok(()) }));

        assert_eq!(&visit_fn, &visit_fn);
    }

    #[test]
    fn partial_eq_returns_false_for_different_instance() {
        let visit_fn_0 = VisitFn(|_| Box::pin(async { Result::<(), ()>::Ok(()) }));
        let visit_fn_1 = VisitFn(|_| Box::pin(async { Result::<(), ()>::Ok(()) }));

        assert_ne!(&visit_fn_0, &visit_fn_1);
    }
}
